SET FOREIGN_KEY_CHECKS=0;




CREATE TABLE T_CMPNNT
(
	id INTEGER NOT NULL,
	name VARCHAR(200) NOT NULL,
	name_tr VARCHAR(200),
	PRIMARY KEY (id)

) 
;


CREATE TABLE T_CMPNY
(
	id INTEGER NOT NULL,
	name VARCHAR(255) NOT NULL,
	phone_num VARCHAR(50),
	fax_num VARCHAR(50),
	adress VARCHAR(255),
	description TEXT,
	email VARCHAR(100),
	PRIMARY KEY (id)

) 
;


CREATE TABLE T_CMPNY_DATA
(
	cmpny_id INTEGER NOT NULL,
	description TEXT,
	PRIMARY KEY (cmpny_id)

) 
;


CREATE TABLE T_CMPNY_NACE_CODE
(
	cmpny_id INTEGER NOT NULL,
	nace_code_id INTEGER NOT NULL,
	PRIMARY KEY (cmpny_id, nace_code_id),
	KEY (cmpny_id),
	KEY (nace_code_id)

) 
;


CREATE TABLE T_CMPNY_PRJ_DATA
(
	prj_id INTEGER NOT NULL,
	cmpny_id INTEGER NOT NULL,
	PRIMARY KEY (prj_id, cmpny_id)

) 
;


CREATE TABLE T_CMPNY_PSNL
(
	user_id INTEGER NOT NULL,
	cmpny_id INTEGER NOT NULL,
	PRIMARY KEY (user_id, cmpny_id),
	KEY (cmpny_id)

) 
;


CREATE TABLE T_CNSLTNT
(
	user_id INTEGER NOT NULL,
	company VARCHAR(200),
	description TEXT,
	PRIMARY KEY (user_id)

) 
;


CREATE TABLE T_DOC
(
	id INTEGER NOT NULL,
	doc BLOB,
	description VARCHAR(255),
	PRIMARY KEY (id)

) 
;


CREATE TABLE T_EQPMNT
(
	id INTEGER NOT NULL,
	name VARCHAR(200) NOT NULL,
	name_tr VARCHAR(200),
	PRIMARY KEY (id)

) 
;


CREATE TABLE T_FLOW
(
	id INTEGER NOT NULL,
	cmpny_id INTEGER,
	flow_name_id INTEGER NOT NULL,
	qntty DECIMAL(10,3),
	qntty_unit INTEGER,
	cost DECIMAL(10,2),
	cost_unit INTEGER,
	ep DECIMAL(10,2),
	ep_unit INTEGER,
	PRIMARY KEY (id),
	KEY (cmpny_id),
	KEY (flow_name_id),
	KEY (qntty_unit),
	KEY (cost_unit),
	KEY (ep_unit)

) 
;


CREATE TABLE T_FLOW_CMPNNT
(
	flow_id INTEGER NOT NULL,
	cmpnnt_id INTEGER NOT NULL,
	PRIMARY KEY (flow_id, cmpnnt_id),
	KEY (cmpnnt_id),
	KEY (flow_id)

) 
;


CREATE TABLE T_FLOW_NAME
(
	id INTEGER NOT NULL,
	name VARCHAR(200) NOT NULL,
	name_tr VARCHAR(200),
	PRIMARY KEY (id)

) 
;


CREATE TABLE T_FLOW_PRCSS
(
	flow_id INTEGER NOT NULL,
	prcss_id INTEGER NOT NULL,
	PRIMARY KEY (flow_id, prcss_id),
	KEY (flow_id),
	KEY (prcss_id)

) 
;


CREATE TABLE T_NACE_CODE
(
	id INTEGER NOT NULL,
	code VARCHAR(10),
	name VARCHAR(255),
	name_tr VARCHAR(255),
	PRIMARY KEY (id)

) 
;


CREATE TABLE T_PRCSS
(
	id INTEGER NOT NULL,
	cmpny_id INTEGER,
	prcss_name_id INTEGER NOT NULL,
	PRIMARY KEY (id),
	KEY (cmpny_id),
	KEY (prcss_name_id)

) 
;


CREATE TABLE T_PRCSS_EQPMNT
(
	prcss_id INTEGER NOT NULL,
	eqpmnt_id INTEGER NOT NULL,
	PRIMARY KEY (prcss_id, eqpmnt_id),
	KEY (eqpmnt_id),
	KEY (prcss_id)

) 
;


CREATE TABLE T_PRCSS_NAME
(
	id INTEGER NOT NULL,
	name VARCHAR(200) NOT NULL,
	name_tr VARCHAR(200),
	PRIMARY KEY (id)

) 
;


CREATE TABLE T_PRDCT
(
	id INTEGER NOT NULL,
	cmpny_id INTEGER,
	name VARCHAR(200) NOT NULL,
	PRIMARY KEY (id),
	KEY (cmpny_id)

) 
;


CREATE TABLE T_PRJ
(
	id INTEGER NOT NULL,
	start_date DATE NOT NULL,
	end_date DATE,
	status_id INTEGER NOT NULL,
	description TEXT,
	PRIMARY KEY (id),
	KEY (status_id)

) 
;


CREATE TABLE T_PRJ_ACSS_CMPNY
(
	cmpny_id INTEGER NOT NULL,
	prj_id INTEGER NOT NULL,
	read_acss NCHAR(10),
	write_acss NCHAR(10),
	delete_acss NCHAR(10),
	PRIMARY KEY (cmpny_id, prj_id),
	KEY (cmpny_id),
	KEY (prj_id)

) 
;


CREATE TABLE T_PRJ_ACSS_USER
(
	user_id INTEGER NOT NULL,
	prj_id INTEGER NOT NULL,
	read_acss NCHAR(10),
	write_acss NCHAR(10),
	delete_acss NCHAR(10),
	PRIMARY KEY (user_id, prj_id),
	KEY (prj_id),
	KEY (user_id)

) 
;


CREATE TABLE T_PRJ_CMPNY
(
	prj_id INTEGER NOT NULL,
	cmpny_id INTEGER NOT NULL,
	PRIMARY KEY (prj_id, cmpny_id),
	KEY (cmpny_id),
	KEY (prj_id)

) 
;


CREATE TABLE T_PRJ_CNSLTNT
(
	prj_id INTEGER NOT NULL,
	cnsltnt_id INTEGER NOT NULL,
	PRIMARY KEY (prj_id, cnsltnt_id),
	KEY (cnsltnt_id),
	KEY (prj_id)

) 
;


CREATE TABLE T_PRJ_CNTCT_PRSNL
(
	prj_id INTEGER NOT NULL,
	usr_id INTEGER NOT NULL,
	description TEXT,
	PRIMARY KEY (prj_id, usr_id),
	KEY (usr_id)

) 
;


CREATE TABLE T_PRJ_DOC
(
	doc_id INTEGER NOT NULL,
	prj_id INTEGER NOT NULL,
	PRIMARY KEY (doc_id, prj_id),
	KEY (doc_id),
	KEY (prj_id)

) 
;


CREATE TABLE T_ROLE
(
	id INTEGER NOT NULL,
	name VARCHAR(100) NOT NULL,
	PRIMARY KEY (id)

) 
;


CREATE TABLE T_STATUS
(
	id INTEGER NOT NULL,
	name VARCHAR(200),
	name_tr VARCHAR(200),
	PRIMARY KEY (id)

) 
;


CREATE TABLE T_UNIT
(
	id INTEGER NOT NULL,
	name VARCHAR(200) NOT NULL,
	name_tr VARCHAR(200),
	PRIMARY KEY (id)

) 
;


CREATE TABLE T_USER
(
	id INTEGER NOT NULL,
	name VARCHAR(100) NOT NULL,
	surname VARCHAR(100) NOT NULL,
	user_name VARCHAR(50) NOT NULL,
	psswrd VARCHAR(50) NOT NULL,
	role_id INTEGER,
	cmpny_id INTEGER,
	title VARCHAR(255),
	phone_num_1 VARCHAR(50),
	phone_num_2 VARCHAR(50),
	fax_num VARCHAR(50),
	adress TEXT,
	email VARCHAR(100),
	description TEXT,
	linkedin_user BOOL,
	photo BLOB,
	PRIMARY KEY (id),
	KEY (cmpny_id),
	KEY (role_id)

) 
;


CREATE TABLE T_USER_LOG
(
	id INTEGER NOT NULL,
	user_id INTEGER,
	PRIMARY KEY (id),
	KEY (user_id)

) 
;



SET FOREIGN_KEY_CHECKS=1;


ALTER TABLE T_CMPNY_DATA ADD CONSTRAINT FK_T_CMPNY_PRJ_T_CMPNY 
	FOREIGN KEY (cmpny_id) REFERENCES T_CMPNY (id)
;

ALTER TABLE T_CMPNY_NACE_CODE ADD CONSTRAINT FK_T_CMPNY_NACE_CODE_T_CMPNY 
	FOREIGN KEY (cmpny_id) REFERENCES T_CMPNY (id)
;

ALTER TABLE T_CMPNY_NACE_CODE ADD CONSTRAINT FK_T_CMPNY_NACE_CODE_T_NACE_CODE 
	FOREIGN KEY (nace_code_id) REFERENCES T_NACE_CODE (id)
;

ALTER TABLE T_CMPNY_PSNL ADD CONSTRAINT FK_T_CMPNY_PSNL_T_CMPNY 
	FOREIGN KEY (cmpny_id) REFERENCES T_CMPNY (id)
;

ALTER TABLE T_CNSLTNT ADD CONSTRAINT FK_T_CNSLTNT_T_USER 
	FOREIGN KEY (user_id) REFERENCES T_USER (id)
;

ALTER TABLE T_FLOW ADD CONSTRAINT FK_T_FLOW_T_CMPNY_DATA 
	FOREIGN KEY (cmpny_id) REFERENCES T_CMPNY_DATA (cmpny_id)
;

ALTER TABLE T_FLOW ADD CONSTRAINT FK_T_FLOW_T_FLOW_NAME 
	FOREIGN KEY (flow_name_id) REFERENCES T_FLOW_NAME (id)
;

ALTER TABLE T_FLOW ADD CONSTRAINT FK_T_FLOW_T_UNIT_QNTTY 
	FOREIGN KEY (qntty_unit) REFERENCES T_UNIT (id)
;

ALTER TABLE T_FLOW ADD CONSTRAINT FK_T_FLOW_T_UNIT_COST 
	FOREIGN KEY (cost_unit) REFERENCES T_UNIT (id)
;

ALTER TABLE T_FLOW ADD CONSTRAINT FK_T_FLOW_T_UNIT_EP 
	FOREIGN KEY (ep_unit) REFERENCES T_UNIT (id)
;

ALTER TABLE T_FLOW_CMPNNT ADD CONSTRAINT FK_T_FLOW_CMPNNT_T_CMPNNT 
	FOREIGN KEY (cmpnnt_id) REFERENCES T_CMPNNT (id)
;

ALTER TABLE T_FLOW_CMPNNT ADD CONSTRAINT FK_T_FLOW_CMPNNT_T_FLOW 
	FOREIGN KEY (flow_id) REFERENCES T_FLOW (id)
;

ALTER TABLE T_FLOW_PRCSS ADD CONSTRAINT FK_T_FLOW_PRCSS_T_FLOW 
	FOREIGN KEY (flow_id) REFERENCES T_FLOW (id)
;

ALTER TABLE T_FLOW_PRCSS ADD CONSTRAINT FK_T_FLOW_PRCSS_T_PRCSS 
	FOREIGN KEY (prcss_id) REFERENCES T_PRCSS (id)
;

ALTER TABLE T_PRCSS ADD CONSTRAINT FK_T_PRCSS_T_CMPNY_DATA 
	FOREIGN KEY (cmpny_id) REFERENCES T_CMPNY_DATA (cmpny_id)
;

ALTER TABLE T_PRCSS ADD CONSTRAINT FK_T_PRCSS_T_PRCSS_NAME 
	FOREIGN KEY (prcss_name_id) REFERENCES T_PRCSS_NAME (id)
;

ALTER TABLE T_PRCSS_EQPMNT ADD CONSTRAINT FK_T_PRCSS_EQPMNT_T_EQPMNT 
	FOREIGN KEY (eqpmnt_id) REFERENCES T_EQPMNT (id)
;

ALTER TABLE T_PRCSS_EQPMNT ADD CONSTRAINT FK_T_PRCSS_EQPMNT_T_PRCSS 
	FOREIGN KEY (prcss_id) REFERENCES T_PRCSS (id)
;

ALTER TABLE T_PRDCT ADD CONSTRAINT FK_T_PRDCT_T_CMPNY_DATA 
	FOREIGN KEY (cmpny_id) REFERENCES T_CMPNY_DATA (cmpny_id)
;

ALTER TABLE T_PRJ ADD CONSTRAINT FK_T_PRJ_T_STATUS 
	FOREIGN KEY (status_id) REFERENCES T_STATUS (id)
;

ALTER TABLE T_PRJ_ACSS_CMPNY ADD CONSTRAINT FK_T_PRJ_ACSS_CMPNY_T_CMPNY 
	FOREIGN KEY (cmpny_id) REFERENCES T_CMPNY (id)
;

ALTER TABLE T_PRJ_ACSS_CMPNY ADD CONSTRAINT FK_T_PRJ_ACSS_CMPNY_T_PRJ 
	FOREIGN KEY (prj_id) REFERENCES T_PRJ (id)
;

ALTER TABLE T_PRJ_ACSS_USER ADD CONSTRAINT FK_T_PRJ_ACSS_USER_T_PRJ 
	FOREIGN KEY (prj_id) REFERENCES T_PRJ (id)
;

ALTER TABLE T_PRJ_ACSS_USER ADD CONSTRAINT FK_T_PRJ_ACSS_USER_T_USER 
	FOREIGN KEY (user_id) REFERENCES T_USER (id)
;

ALTER TABLE T_PRJ_CMPNY ADD CONSTRAINT FK_T_PRJ_CMPNY_T_CMPNY 
	FOREIGN KEY (cmpny_id) REFERENCES T_CMPNY (id)
;

ALTER TABLE T_PRJ_CMPNY ADD CONSTRAINT FK_T_PRJ_CMPNY_T_PRJ 
	FOREIGN KEY (prj_id) REFERENCES T_PRJ (id)
;

ALTER TABLE T_PRJ_CNSLTNT ADD CONSTRAINT FK_T_PRJ_CNSLTNT_T_CNSLTNT 
	FOREIGN KEY (cnsltnt_id) REFERENCES T_CNSLTNT (user_id)
;

ALTER TABLE T_PRJ_CNSLTNT ADD CONSTRAINT FK_T_PRJ_CNSLTNT_T_PRJ 
	FOREIGN KEY (prj_id) REFERENCES T_PRJ (id)
;

ALTER TABLE T_PRJ_CNTCT_PRSNL ADD CONSTRAINT FK_T_PRJ_CNTCT_PRSNL_T_USER 
	FOREIGN KEY (usr_id) REFERENCES T_USER (id)
;

ALTER TABLE T_PRJ_DOC ADD CONSTRAINT FK_T_PRJ_DOC_T_DOC 
	FOREIGN KEY (doc_id) REFERENCES T_DOC (id)
;

ALTER TABLE T_PRJ_DOC ADD CONSTRAINT FK_T_PRJ_DOC_T_PRJ 
	FOREIGN KEY (prj_id) REFERENCES T_PRJ (id)
;

ALTER TABLE T_USER ADD CONSTRAINT FK_T_USER_T_CMPNY 
	FOREIGN KEY (cmpny_id) REFERENCES T_CMPNY (id)
;

ALTER TABLE T_USER ADD CONSTRAINT FK_T_USER_T_ROLE 
	FOREIGN KEY (role_id) REFERENCES T_ROLE (id)
;

ALTER TABLE T_USER_LOG ADD CONSTRAINT FK_T_USER_LOG_T_USER 
	FOREIGN KEY (user_id) REFERENCES T_USER (id)
;
